generate_features:  True
preprocess:         True
train_model:        True
params:
    species1:   'your/dir/to/parameter/species1'
    species2:   'your/dir/to/parameter/species2'

# Input for generate fearues
descriptor: 
    # Input feature
    type:               'symmetry_function'
    # Reference data
    struct_list:        'structure_list'
    refdata_format:     'vasp-out'
    compress_outcar:    True
    save_directory:     'data'
    save_list:          'total_list'
    absolute_path:      True
    read_force:         True
    read_stress:        True 
    dx_save_sparse:     True

# Input for preprocess
preprocessing: 
    # Train/validation
    data_list:              'total_list'
    train_list:             'train_list'
    valid_list:             'valid_list' 
    valid_rate:             0.1
    shuffle:                True
    # Scaling parameters
    calc_scale:             True
    scale_type:             'minmax'
    scale_width:            1.0
    # PCA parameters
    calc_pca:               True
    pca_whiten:             True
    min_whiten_level:       1.0e-8
    # Atomic weights
    calc_atomic_weights:    False

# Input for traning
neural_network:
    # Running mode
    train:              True
    train_list:         'train_list'
    valid_list:         'valid_list' 
    test:               False
    test_list:          'test_list'
    add_NNP_ref:        False
    ref_list:           'ref_list'
    train_atomic_E:     False
    use_force:          True
    use_stress:         True
    shuffle_dataloader: True
    # Network
    nodes:              '30-30'
    acti_func:          'sigmoid'
    double_precision:   True
    weight_initializer:
        type:           'xavier normal'
    dropout:            False
    use_scale:          True
    use_pca:            True
    use_atomic_weights: False
    weight_modifier: 
        type:           null
    # Optimization
    optimizer:
        method:         'Adam'
    batch_size:         8
    full_batch:         False
    total_epoch:        1000
    learning_rate:      0.0001
    decay_rate:         null
    l2_regularization:  1.0e-6
    # Loss function
    loss_scale:         1.
    E_loss_type:        1
    F_loss_type:        1
    energy_coeff:       1.
    force_coeff:        0.1 
    stress_coeff:       1.0e-6
    # Logging & saving
    show_interval:          10
    save_interval:          0
    energy_criteria:        null
    force_criteria:         null
    stress_criteria:        null
    print_structure_rmse:   False
    # Continue
    continue:               null
    clear_prev_status:      False
    clear_prev_optimizer:   False
    start_epoch:            1
    # Parallelism
    use_gpu:            True
    GPU_number:         null
    inter_op_threads:   0
    intra_op_threads:   0
    load_data_to_gpu:   False
    subprocesses:       0 

